development:
  adapter: postgresql
  encoding: unicode
  database: nuuvem_development
  pool: 2
  host: postgres
  username: 'postgres'
  password: 'postgres'

test:
  adapter: postgresql
  encoding: unicode
  database: nuuvem_test
  pool: 2
  host: postgres
  username: 'postgres'
  password: 'postgres'